### ISSUE TITLE
Remove hirak/prestissimo from init-site

### ISSUE THREAD

**Issue by lmakarov** [docksal/example-symfony-skeleton#1]
[hirak/prestissimo](https://github.com/sean-e-dietrich/docksal-symfony-skeleton/blob/ab7f39d34b69afa353373728e634c38f38e2cecc/.docksal/commands/init-site#L42) is already included in the latest [docksal/cli](https://github.com/docksal/service-cli/blob/develop/7.1/Dockerfile#L303) images.

**Comment by sean-e-dietrich** [comment]
Great! Thanks for the confirmation!
